const fs = require("node:fs");
const path = require("node:path");
const postcss = require("postcss");
const valueParser = require("postcss-value-parser");

const ROOT = path.resolve(__dirname, "..");
const entries = require("../css/entries.json");
const outputs = { popup: "popup.css", content: "styles.css" };

function dependencies(value) {
  const names = new Set();
  valueParser(value).walk((node) => {
    if (node.type === "function" && node.value === "url") return false;
    if (node.type === "function" && node.value === "var") {
      names.add(node.nodes.find((item) => item.type === "word").value);
    }
  });
  return names;
}

function compile(kind) {
  if (!entries[kind]) throw new Error(`Unknown CSS entry: ${kind}`);
  const root = postcss.root();
  for (const file of entries[kind]) {
    root.append(postcss.parse(fs.readFileSync(path.join(ROOT, file), "utf8"), { from: file }));
  }
  // Each runtime context receives only the shared tokens it actually uses.
  const tokens = new Map();
  const used = new Set();
  root.walkDecls((decl) => {
    if (decl.prop.startsWith("--lx-")) tokens.set(decl.prop, decl);
    else for (const name of dependencies(decl.value)) used.add(name);
  });
  for (const name of used) {
    if (tokens.has(name)) {
      for (const dependency of dependencies(tokens.get(name).value)) used.add(dependency);
    }
  }
  for (const [name, decl] of tokens) if (!used.has(name)) decl.remove();
  root.walkComments((comment) => comment.remove());
  // Private source-token names are descriptive in modules and compact in the
  // generated assets. Use the complete shared catalogue for stable names across
  // both contexts. Public theme/player variables are deliberately untouched.
  const compactNames = new Map([...tokens.keys()].sort().map((name, index) =>
    [name, `--lx-${index.toString(36)}`]));
  root.walkDecls((decl) => {
    if (compactNames.has(decl.prop)) decl.prop = compactNames.get(decl.prop);
    const value = valueParser(decl.value);
    value.walk((node) => {
      if (node.type === "function" && node.value === "url") return false;
      if (node.type === "word" && compactNames.has(node.value)) node.value = compactNames.get(node.value);
      if (node.type === "space") node.value = " ";
      if (node.type === "function" || node.type === "div") { node.before = ""; node.after = ""; }
    });
    decl.value = value.toString();
  });
  // Compact whitespace only. Do not reorder rules, lower specificity, rewrite
  // shorthand values, or remove browser fallbacks to save a handful of bytes.
  root.walk((node) => {
    node.raws = {};
    if (node.type === "decl") {
      node.raws.before = "";
      node.raws.between = ":";
      if (node.important) node.raws.important = " !important";
    } else {
      node.raws.before = node.parent.type === "root" ? "\n" : "";
      node.raws.between = "";
      node.raws.after = "";
      node.raws.semicolon = true;
    }
  });
  root.raws.after = "\n";
  return "/* Generated by npm run build:css. Edit css/ sources. */" + root.toString();
}

function build({ check = false } = {}) {
  for (const [kind, file] of Object.entries(outputs)) {
    const css = compile(kind);
    const target = path.join(ROOT, file);
    if (check) {
      if (!fs.existsSync(target) || fs.readFileSync(target, "utf8") !== css) {
        throw new Error(`${file} is stale. Run npm run build:css.`);
      }
    } else fs.writeFileSync(target, css);
    console.log(`${file}: ${Buffer.byteLength(css)} bytes${check ? " (current)" : ""}`);
  }
}

if (require.main === module) build({ check: process.argv.includes("--check") });
module.exports = { compile, build, dependencies };
